China y Rusia en el Nuevo desorden mundial  
¿ Puede Kosovo lograr la independencia sin el consentimiento tácito de Rusia , y puede haber una solución política y humanitaria a la tragedia en Darfur sin la buena voluntad activa de China ?  
Las dos crisis no tienen nada en común , pero su-nonhum-sg resolución dependerá en gran medida de si estos dos miembros permanentes del Consejo de seguridad de las naciones unidas utilizan su-nonhum-sg poder de veto .  
Comparar las respectivas capacidades de Rusia y China de bloquear iniciativas internacionales claves no tiene sentido en si mismo , pero dummy-it constituye una herramienta útil para comprender la transformación del sistema internacional que hoy está teniendo lugar como consecuencia directa del relativo declive del poder mundial de Ee.uu. desde ese punto de la profundización del caos en el Oriente próximo plantea tanto oportunidades como riesgos para Rusia y China , que puedan obligarlas a definir los papeles que desean jugar y las imágenes que quieren proyectar al mundo .  
La pregunta clave es : ¿ dummy-nonhum Está Rusia dando pasos agigantados en la " dirección equivocada " , mientras China está dando pasos " minúsculos " en la " dirección correcta " ?  
En lo superficial , Rusia y China pueden dar la impresión de estar siguiendo el mismo camino cuando ambas proclaman que se enorgullecen de estar " de regreso " en la escena mundial .  
Sin embargo , esta afirmación significa cosas diferentes para cada país .  
Para China , país que tiene una profunda confianza en si mismo , estar " de regreso " significa simplemente recuperar su-nonhum-sg centralidad histórica en el mundo tras una ausencia de más de dos siglos .  
Después de todo , a fines del siglo dieciocho China era el primer productor mundial de bienes manufacturados , y se percibe a si misma como un centro de civilización sin parangón en Asia , y quizás en el mundo entero .  
La renovada confianza en si misma de China se basa en su-nonhum-sg notable destreza económica , que se deriva no de su-nonhum-sg recursos naturales sino de su-nonhum-sg productividad y creatividad .  
Cualesquiera sean las grandes tensiones políticas , sociales y económicas que puedan existir , en China hay un factor de " sensación de bienestar " , un sentido de progreso , y los Juegos olímpicos del 2008 en Beijing figuran como el momento simbólico que proclamará al mundo la escala de los logros del país .  
Sobre todo , con la excepción del tema de Taiwán , China es una potencia satisfecha con el status quo en lo referente a la evolución del sistema internacional ; es un actor paciente que-hum encuentra perfectamente legítimo comportarse y ser visto como la potencia número dos del mundo .  
En contraste , los rusos siguen sintiendo inseguridad acerca de su-pl estatus en el mundo .  
El explosivo comportamiento " revisionista " de Rusia en la víspera de la última cumbre del G8 es una señal de la naturaleza " insatisfecha " del Kremlin .  
Puesto que dummy-they saben que dummy-they son menos potentes , especialmente en términos demográficos y económicos , los rusos sienten que dummy-they tienen que hacer " más " .  
Para ellos , decir que Rusia está " de regreso " dummy-it significa que los humillantes años de Yeltsin son cosa del pasado , y que ahora deben ser tratados como iguales , particularmente por Estados unidos .  
Los rusos sienten nostalgia no por la Guerra fría en si misma , sino por el estatus internacional que perdieron cuando dummy-nonhum llegó a su-nonhum-sg fin .  
Ahora que Estados unidos ya no es una " hiperpotencia " sin rivales estratégicos , Rusia ha reafirmado su-nonhum-sg condición de " superpotencia " , afirmación que no necesariamente está respaldada por la realidad .  
A diferencia de los chinos , los rusos no crean riqueza económica , sino que meramente dummy-they explotan su-pl recursos energéticos y minerales .  
Más aún , a diferencia de los chinos , no siempre se dummy-they han sentido confiados de su-pl posición en el mundo .  
Dividida entre Europa y Asia en términos políticos y culturales , víctima de un instinto oscuro y narcisista que tiñe su-nonhum-sg lectura del pasado y su-nonhum-sg visiones del futuro , no debería sorprender a nadie el que Rusia hoy se esté comportando como una potencia " revisionista " .  
Insatisfechos con su-nonhum-sg identidad propia , es natural que los rusos sientan la necesidad de exigir cambios que los hagan sentirse más seguros y orgullosos .  
Hace menos de 20 años la República checa y Polonia eran parte de su-nonhum-sg esfera de influencia , de modo que dummy-it es comprensible que no puedan aceptar que Estados unidos imponga unilateralmente su-nonhum-sg sistema de seguridad allí .  
Por supuesto , en su-nonhum-sg juicios respectivos sobre Rusia y China , los países de Occidente - y particularmente los europeos - pueden estar demostrando emociones selectivas .  
" Nosotros " tendemos a exigir menos a China que a Rusia , porque dummy-we tendemos a ver a Rusia como " europea " ( al menos en lo cultural ) .  
Como resultado , la cultura de violencia y provocación verbal que está ganando terreno en la Rusia de putin dummy-nonhum nos perturba profundamente , mientras que dummy-we tendemos a juzgar las malas obras de China con un mayor sentido de distancia , si dummy-it es que no de indiferencia .  
Sin embargo , las diferencias actuales entre China y Rusia pueden demostrar ser menos significativas en el día de mañana si el deterioro del Oriente próximo impone un sentido de responsabilidad colectiva en los cinco miembros permanentes del Consejo de seguridad de la onu .  
Una cosa es que Rusia y China exploten las crecientes dificultades que Ee.uu. sufre desde Gaza a Kabul ; otra muy diferente dummy-it es que la situación empeore hasta un punto de desestabilización general en la región .  
dummy-I He hecho , los crecientes problemas en el Oriente próximo pueden dar un sentido de los límites a Rusia y China , al obligarles a calcular no en términos de su-pl " valor de reto " global frente a Occidente , sino en términos de su-pl capacidad de hacer una contribución positiva y estabilizadora al orden mundial .  
